// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// irtc_calcfx
SEXP irtc_calcfx(SEXP sFx, SEXP sRprobs, SEXP sRespIndList, SEXP sResp, int n_threads);
RcppExport SEXP _IRTC_irtc_calcfx(SEXP sFxSEXP, SEXP sRprobsSEXP, SEXP sRespIndListSEXP, SEXP sRespSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sFx(sFxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sRprobs(sRprobsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sRespIndList(sRespIndListSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sResp(sRespSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_calcfx(sFx, sRprobs, sRespIndList, sResp, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_calc_exp
Rcpp::List irtc_rcpp_calc_exp(int NP, Rcpp::NumericVector rprobs, Rcpp::NumericVector A, Rcpp::NumericMatrix INDEXIPNO, Rcpp::NumericVector INDEXIPLIST2, Rcpp::NumericVector ESTXSIINDEX, int C, Rcpp::NumericMatrix ITEMWT, int NR, int TP);
RcppExport SEXP _IRTC_irtc_rcpp_calc_exp(SEXP NPSEXP, SEXP rprobsSEXP, SEXP ASEXP, SEXP INDEXIPNOSEXP, SEXP INDEXIPLIST2SEXP, SEXP ESTXSIINDEXSEXP, SEXP CSEXP, SEXP ITEMWTSEXP, SEXP NRSEXP, SEXP TPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NP(NPSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rprobs(rprobsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type INDEXIPNO(INDEXIPNOSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type INDEXIPLIST2(INDEXIPLIST2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ESTXSIINDEX(ESTXSIINDEXSEXP);
    Rcpp::traits::input_parameter< int >::type C(CSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type ITEMWT(ITEMWTSEXP);
    Rcpp::traits::input_parameter< int >::type NR(NRSEXP);
    Rcpp::traits::input_parameter< int >::type TP(TPSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_calc_exp(NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, NR, TP));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_calc_exp_redefine_vector_na
Rcpp::NumericVector irtc_rcpp_calc_exp_redefine_vector_na(Rcpp::NumericVector A, double val);
RcppExport SEXP _IRTC_irtc_rcpp_calc_exp_redefine_vector_na(SEXP ASEXP, SEXP valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type val(valSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_calc_exp_redefine_vector_na(A, val));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_calc_prob
Rcpp::List irtc_rcpp_calc_prob(Rcpp::NumericVector A, Rcpp::IntegerVector dimA, Rcpp::NumericVector xsi, Rcpp::IntegerVector maxcat, Rcpp::NumericMatrix AXsi0, Rcpp::IntegerVector iIndex, Rcpp::NumericMatrix theta, Rcpp::NumericVector B);
RcppExport SEXP _IRTC_irtc_rcpp_calc_prob(SEXP ASEXP, SEXP dimASEXP, SEXP xsiSEXP, SEXP maxcatSEXP, SEXP AXsi0SEXP, SEXP iIndexSEXP, SEXP thetaSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dimA(dimASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type xsi(xsiSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type maxcat(maxcatSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type AXsi0(AXsi0SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iIndex(iIndexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_calc_prob(A, dimA, xsi, maxcat, AXsi0, iIndex, theta, B));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_calc_prob_subtract_max
Rcpp::NumericMatrix irtc_rcpp_calc_prob_subtract_max(Rcpp::NumericMatrix rr0M, int NI, int NK, int TP);
RcppExport SEXP _IRTC_irtc_rcpp_calc_prob_subtract_max(SEXP rr0MSEXP, SEXP NISEXP, SEXP NKSEXP, SEXP TPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type rr0M(rr0MSEXP);
    Rcpp::traits::input_parameter< int >::type NI(NISEXP);
    Rcpp::traits::input_parameter< int >::type NK(NKSEXP);
    Rcpp::traits::input_parameter< int >::type TP(TPSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_calc_prob_subtract_max(rr0M, NI, NK, TP));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_calc_prob_subtract_max_exp
Rcpp::NumericVector irtc_rcpp_calc_prob_subtract_max_exp(Rcpp::NumericVector rr0, Rcpp::IntegerVector dim_rr);
RcppExport SEXP _IRTC_irtc_rcpp_calc_prob_subtract_max_exp(SEXP rr0SEXP, SEXP dim_rrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rr0(rr0SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dim_rr(dim_rrSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_calc_prob_subtract_max_exp(rr0, dim_rr));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_irtc_mml_calc_prob_R_outer_Btheta
Rcpp::NumericVector irtc_rcpp_irtc_mml_calc_prob_R_outer_Btheta(Rcpp::NumericVector Btheta, Rcpp::NumericVector B_dd, Rcpp::NumericVector theta_dd, Rcpp::IntegerVector dim_Btheta);
RcppExport SEXP _IRTC_irtc_rcpp_irtc_mml_calc_prob_R_outer_Btheta(SEXP BthetaSEXP, SEXP B_ddSEXP, SEXP theta_ddSEXP, SEXP dim_BthetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Btheta(BthetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type B_dd(B_ddSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_dd(theta_ddSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dim_Btheta(dim_BthetaSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_irtc_mml_calc_prob_R_outer_Btheta(Btheta, B_dd, theta_dd, dim_Btheta));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_irtc_mml_calc_prob_R_normalize_rprobs
Rcpp::NumericVector irtc_rcpp_irtc_mml_calc_prob_R_normalize_rprobs(Rcpp::NumericVector rr, Rcpp::IntegerVector dim_rr);
RcppExport SEXP _IRTC_irtc_rcpp_irtc_mml_calc_prob_R_normalize_rprobs(SEXP rrSEXP, SEXP dim_rrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rr(rrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dim_rr(dim_rrSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_irtc_mml_calc_prob_R_normalize_rprobs(rr, dim_rr));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_calc_suff_stat
Rcpp::List irtc_rcpp_calc_suff_stat(Rcpp::IntegerMatrix resp, Rcpp::IntegerMatrix resp_ind, int maxK, int nitems, Rcpp::NumericVector pweights, Rcpp::NumericMatrix cA);
RcppExport SEXP _IRTC_irtc_rcpp_calc_suff_stat(SEXP respSEXP, SEXP resp_indSEXP, SEXP maxKSEXP, SEXP nitemsSEXP, SEXP pweightsSEXP, SEXP cASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type resp(respSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type resp_ind(resp_indSEXP);
    Rcpp::traits::input_parameter< int >::type maxK(maxKSEXP);
    Rcpp::traits::input_parameter< int >::type nitems(nitemsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pweights(pweightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cA(cASEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_calc_suff_stat(resp, resp_ind, maxK, nitems, pweights, cA));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_theta_sq
Rcpp::NumericMatrix irtc_rcpp_theta_sq(Rcpp::NumericMatrix theta);
RcppExport SEXP _IRTC_irtc_rcpp_theta_sq(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_theta_sq(theta));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_interval_index
Rcpp::NumericVector irtc_rcpp_interval_index(Rcpp::NumericMatrix MATR, Rcpp::NumericVector RN);
RcppExport SEXP _IRTC_irtc_rcpp_interval_index(SEXP MATRSEXP, SEXP RNSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type MATR(MATRSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type RN(RNSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_interval_index(MATR, RN));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_mml_2pl_mstep_item_slopes_suffstat
Rcpp::List irtc_rcpp_mml_2pl_mstep_item_slopes_suffstat(Rcpp::NumericVector rprobs, Rcpp::IntegerVector items_temp, Rcpp::NumericMatrix theta, int dd, int LIT, int TP, int nitems, Rcpp::IntegerVector maxcat, int maxK, Rcpp::NumericMatrix itemwt, Rcpp::NumericMatrix xxf_, Rcpp::NumericMatrix xbar_, Rcpp::NumericMatrix xbar2_, Rcpp::CharacterVector irtmodel, Rcpp::NumericMatrix xtemp_, Rcpp::IntegerVector items_conv, int n_threads);
RcppExport SEXP _IRTC_irtc_rcpp_mml_2pl_mstep_item_slopes_suffstat(SEXP rprobsSEXP, SEXP items_tempSEXP, SEXP thetaSEXP, SEXP ddSEXP, SEXP LITSEXP, SEXP TPSEXP, SEXP nitemsSEXP, SEXP maxcatSEXP, SEXP maxKSEXP, SEXP itemwtSEXP, SEXP xxf_SEXP, SEXP xbar_SEXP, SEXP xbar2_SEXP, SEXP irtmodelSEXP, SEXP xtemp_SEXP, SEXP items_convSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rprobs(rprobsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type items_temp(items_tempSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type dd(ddSEXP);
    Rcpp::traits::input_parameter< int >::type LIT(LITSEXP);
    Rcpp::traits::input_parameter< int >::type TP(TPSEXP);
    Rcpp::traits::input_parameter< int >::type nitems(nitemsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type maxcat(maxcatSEXP);
    Rcpp::traits::input_parameter< int >::type maxK(maxKSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type itemwt(itemwtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xxf_(xxf_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xbar_(xbar_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xbar2_(xbar2_SEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type irtmodel(irtmodelSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xtemp_(xtemp_SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type items_conv(items_convSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_mml_2pl_mstep_item_slopes_suffstat(rprobs, items_temp, theta, dd, LIT, TP, nitems, maxcat, maxK, itemwt, xxf_, xbar_, xbar2_, irtmodel, xtemp_, items_conv, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_mml_maxcat
Rcpp::IntegerVector irtc_rcpp_mml_maxcat(Rcpp::NumericVector A, Rcpp::IntegerVector dimA);
RcppExport SEXP _IRTC_irtc_rcpp_mml_maxcat(SEXP ASEXP, SEXP dimASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dimA(dimASEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_mml_maxcat(A, dimA));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_prior_normal_density_unequal_means
Rcpp::NumericMatrix irtc_rcpp_prior_normal_density_unequal_means(Rcpp::NumericMatrix theta, Rcpp::NumericMatrix mu, Rcpp::NumericMatrix varInverse, Rcpp::NumericVector COEFF);
RcppExport SEXP _IRTC_irtc_rcpp_prior_normal_density_unequal_means(SEXP thetaSEXP, SEXP muSEXP, SEXP varInverseSEXP, SEXP COEFFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type varInverse(varInverseSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type COEFF(COEFFSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_prior_normal_density_unequal_means(theta, mu, varInverse, COEFF));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_prior_normal_density_equal_means
Rcpp::NumericVector irtc_rcpp_prior_normal_density_equal_means(Rcpp::NumericMatrix theta, Rcpp::NumericMatrix mu, Rcpp::NumericMatrix varInverse, Rcpp::NumericVector COEFF);
RcppExport SEXP _IRTC_irtc_rcpp_prior_normal_density_equal_means(SEXP thetaSEXP, SEXP muSEXP, SEXP varInverseSEXP, SEXP COEFFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type varInverse(varInverseSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type COEFF(COEFFSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_prior_normal_density_equal_means(theta, mu, varInverse, COEFF));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_proto_estep
Rcpp::List irtc_rcpp_proto_estep(IntegerMatrix resp, IntegerVector dimj, NumericVector probs, IntegerMatrix gridcoord, NumericMatrix gw_mat, IntegerVector pattern, NumericVector pweights, IntegerVector group, int ngroup, NumericVector xnode, int Q, int maxK, int n_threads, int want_eap, int want_nodeocc);
RcppExport SEXP _IRTC_irtc_rcpp_proto_estep(SEXP respSEXP, SEXP dimjSEXP, SEXP probsSEXP, SEXP gridcoordSEXP, SEXP gw_matSEXP, SEXP patternSEXP, SEXP pweightsSEXP, SEXP groupSEXP, SEXP ngroupSEXP, SEXP xnodeSEXP, SEXP QSEXP, SEXP maxKSEXP, SEXP n_threadsSEXP, SEXP want_eapSEXP, SEXP want_nodeoccSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type resp(respSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dimj(dimjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type gridcoord(gridcoordSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type gw_mat(gw_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pweights(pweightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xnode(xnodeSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type maxK(maxKSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type want_eap(want_eapSEXP);
    Rcpp::traits::input_parameter< int >::type want_nodeocc(want_nodeoccSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_proto_estep(resp, dimj, probs, gridcoord, gw_mat, pattern, pweights, group, ngroup, xnode, Q, maxK, n_threads, want_eap, want_nodeocc));
    return rcpp_result_gen;
END_RCPP
}
// irtc_rcpp_rowCumsums
Rcpp::NumericMatrix irtc_rcpp_rowCumsums(Rcpp::NumericMatrix input);
RcppExport SEXP _IRTC_irtc_rcpp_rowCumsums(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(irtc_rcpp_rowCumsums(input));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IRTC_irtc_calcfx", (DL_FUNC) &_IRTC_irtc_calcfx, 5},
    {"_IRTC_irtc_rcpp_calc_exp", (DL_FUNC) &_IRTC_irtc_rcpp_calc_exp, 10},
    {"_IRTC_irtc_rcpp_calc_exp_redefine_vector_na", (DL_FUNC) &_IRTC_irtc_rcpp_calc_exp_redefine_vector_na, 2},
    {"_IRTC_irtc_rcpp_calc_prob", (DL_FUNC) &_IRTC_irtc_rcpp_calc_prob, 8},
    {"_IRTC_irtc_rcpp_calc_prob_subtract_max", (DL_FUNC) &_IRTC_irtc_rcpp_calc_prob_subtract_max, 4},
    {"_IRTC_irtc_rcpp_calc_prob_subtract_max_exp", (DL_FUNC) &_IRTC_irtc_rcpp_calc_prob_subtract_max_exp, 2},
    {"_IRTC_irtc_rcpp_irtc_mml_calc_prob_R_outer_Btheta", (DL_FUNC) &_IRTC_irtc_rcpp_irtc_mml_calc_prob_R_outer_Btheta, 4},
    {"_IRTC_irtc_rcpp_irtc_mml_calc_prob_R_normalize_rprobs", (DL_FUNC) &_IRTC_irtc_rcpp_irtc_mml_calc_prob_R_normalize_rprobs, 2},
    {"_IRTC_irtc_rcpp_calc_suff_stat", (DL_FUNC) &_IRTC_irtc_rcpp_calc_suff_stat, 6},
    {"_IRTC_irtc_rcpp_theta_sq", (DL_FUNC) &_IRTC_irtc_rcpp_theta_sq, 1},
    {"_IRTC_irtc_rcpp_interval_index", (DL_FUNC) &_IRTC_irtc_rcpp_interval_index, 2},
    {"_IRTC_irtc_rcpp_mml_2pl_mstep_item_slopes_suffstat", (DL_FUNC) &_IRTC_irtc_rcpp_mml_2pl_mstep_item_slopes_suffstat, 17},
    {"_IRTC_irtc_rcpp_mml_maxcat", (DL_FUNC) &_IRTC_irtc_rcpp_mml_maxcat, 2},
    {"_IRTC_irtc_rcpp_prior_normal_density_unequal_means", (DL_FUNC) &_IRTC_irtc_rcpp_prior_normal_density_unequal_means, 4},
    {"_IRTC_irtc_rcpp_prior_normal_density_equal_means", (DL_FUNC) &_IRTC_irtc_rcpp_prior_normal_density_equal_means, 4},
    {"_IRTC_irtc_rcpp_proto_estep", (DL_FUNC) &_IRTC_irtc_rcpp_proto_estep, 15},
    {"_IRTC_irtc_rcpp_rowCumsums", (DL_FUNC) &_IRTC_irtc_rcpp_rowCumsums, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_IRTC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
