# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

irtc_calcfx <- function(sFx, sRprobs, sRespIndList, sResp, n_threads = 1L) {
    .Call(`_IRTC_irtc_calcfx`, sFx, sRprobs, sRespIndList, sResp, n_threads)
}

irtc_rcpp_calc_exp <- function(NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, NR, TP) {
    .Call(`_IRTC_irtc_rcpp_calc_exp`, NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, NR, TP)
}

irtc_rcpp_calc_exp_redefine_vector_na <- function(A, val) {
    .Call(`_IRTC_irtc_rcpp_calc_exp_redefine_vector_na`, A, val)
}

irtc_rcpp_calc_prob <- function(A, dimA, xsi, maxcat, AXsi0, iIndex, theta, B) {
    .Call(`_IRTC_irtc_rcpp_calc_prob`, A, dimA, xsi, maxcat, AXsi0, iIndex, theta, B)
}

irtc_rcpp_calc_prob_subtract_max <- function(rr0M, NI, NK, TP) {
    .Call(`_IRTC_irtc_rcpp_calc_prob_subtract_max`, rr0M, NI, NK, TP)
}

irtc_rcpp_calc_prob_subtract_max_exp <- function(rr0, dim_rr) {
    .Call(`_IRTC_irtc_rcpp_calc_prob_subtract_max_exp`, rr0, dim_rr)
}

irtc_rcpp_irtc_mml_calc_prob_R_outer_Btheta <- function(Btheta, B_dd, theta_dd, dim_Btheta) {
    .Call(`_IRTC_irtc_rcpp_irtc_mml_calc_prob_R_outer_Btheta`, Btheta, B_dd, theta_dd, dim_Btheta)
}

irtc_rcpp_irtc_mml_calc_prob_R_normalize_rprobs <- function(rr, dim_rr) {
    .Call(`_IRTC_irtc_rcpp_irtc_mml_calc_prob_R_normalize_rprobs`, rr, dim_rr)
}

irtc_rcpp_calc_suff_stat <- function(resp, resp_ind, maxK, nitems, pweights, cA) {
    .Call(`_IRTC_irtc_rcpp_calc_suff_stat`, resp, resp_ind, maxK, nitems, pweights, cA)
}

irtc_rcpp_theta_sq <- function(theta) {
    .Call(`_IRTC_irtc_rcpp_theta_sq`, theta)
}

irtc_rcpp_interval_index <- function(MATR, RN) {
    .Call(`_IRTC_irtc_rcpp_interval_index`, MATR, RN)
}

irtc_rcpp_mml_2pl_mstep_item_slopes_suffstat <- function(rprobs, items_temp, theta, dd, LIT, TP, nitems, maxcat, maxK, itemwt, xxf_, xbar_, xbar2_, irtmodel, xtemp_, items_conv, n_threads = 1L) {
    .Call(`_IRTC_irtc_rcpp_mml_2pl_mstep_item_slopes_suffstat`, rprobs, items_temp, theta, dd, LIT, TP, nitems, maxcat, maxK, itemwt, xxf_, xbar_, xbar2_, irtmodel, xtemp_, items_conv, n_threads)
}

irtc_rcpp_mml_maxcat <- function(A, dimA) {
    .Call(`_IRTC_irtc_rcpp_mml_maxcat`, A, dimA)
}

irtc_rcpp_prior_normal_density_unequal_means <- function(theta, mu, varInverse, COEFF) {
    .Call(`_IRTC_irtc_rcpp_prior_normal_density_unequal_means`, theta, mu, varInverse, COEFF)
}

irtc_rcpp_prior_normal_density_equal_means <- function(theta, mu, varInverse, COEFF) {
    .Call(`_IRTC_irtc_rcpp_prior_normal_density_equal_means`, theta, mu, varInverse, COEFF)
}

irtc_rcpp_proto_estep <- function(resp, dimj, probs, gridcoord, gw_mat, pattern, pweights, group, ngroup, xnode, Q, maxK, n_threads = 1L, want_eap = 0L, want_nodeocc = 0L) {
    .Call(`_IRTC_irtc_rcpp_proto_estep`, resp, dimj, probs, gridcoord, gw_mat, pattern, pweights, group, ngroup, xnode, Q, maxK, n_threads, want_eap, want_nodeocc)
}

irtc_rcpp_rowCumsums <- function(input) {
    .Call(`_IRTC_irtc_rcpp_rowCumsums`, input)
}

